---
- name: Install SSH keys
  authorized_key: user=luke
                  key="{{ item }}"
  with_file:
  - public_keys/luke.pub

- name: Disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh

